[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "twh"
version = "0.1.0"


[project.optional-dependencies]
gui = ["PySide6"]


[project.scripts]
twh = "threewordhash.core:main"
twh_gui = "threewordhash.gui:main"
